# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brian's Corner
email: hello@brianbancroft.ca
description: GIS, Carto, Web, Math. This is the showcase plus blog.
baseurl: ""
url: "brianbancroft.github.io" # the base hostname & protocol for your site
twitter_username: brian_bancroft
github_username:  brianbancroft
linkedin_username: geobrian

# Build settings
markdown: kramdown
